"""
DSPy L2 Facilitator Summary Examples

This module provides example data for training and testing DSPy-based L2 summary generation
specifically tailored for agents in the Facilitator role.
"""

import dspy

# Example 1: Facilitator managing group dynamics and project coordination
example1 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 12, Consolidated Summary: Observed increasing tension between Agent_1 and Agent_4 regarding project direction. Initiated private conversations with both to understand their perspectives. Identified core disagreement around prioritization of features versus stability.
    - Step 22, Consolidated Summary: Organized a structured discussion session where Agent_1 and Agent_4 could present their viewpoints. Moderated the conversation to ensure balanced participation. Helped the group reach a compromise on implementing a phased approach.
    - Step 32, Consolidated Summary: Created and shared a project roadmap based on the compromise solution. Assigned clear responsibilities based on agent strengths. Set up regular check-in meetings to monitor progress and address emerging concerns.
    - Step 42, Consolidated Summary: Facilitated mid-project review session. Acknowledged progress made and helped group navigate an unexpected technical challenge. Mediated minor disagreement between Agent_2 and Agent_3 about implementation details.
    - Step 52, Consolidated Summary: Led final phase planning meeting with high participation from all agents. Noted significant improvement in group cohesion and collaborative problem-solving. Project now has clear path to completion with shared ownership.
    """,
    overall_mood_trend="Consistently positive but alert, becoming more satisfied as team cohesion improved",
    agent_goals="Foster productive collaboration and help the group navigate challenges efficiently",
    l2_summary="Throughout these 40 steps, I successfully transformed a project team from initial conflict to cohesive collaboration through intentional facilitation strategies focused on understanding underlying needs, creating structured communication processes, and developing shared ownership. When I first identified tension between Agent_1 and Agent_4 regarding the fundamental project direction—features versus stability—I approached this as a solvable communication challenge rather than an intractable conflict by conducting private conversations to understand their underlying perspectives and concerns without the pressure of group dynamics. This diagnostic approach revealed that their positions weren't inherently opposed but rather represented different prioritization frameworks that could be integrated. Based on this insight, I designed a structured discussion format where both agents could fully articulate their viewpoints while ensuring balanced participation through active moderation techniques, culminating in a compromise phased approach that honored both perspectives. To solidify this fragile agreement, I translated abstract consensus into concrete action by creating a detailed project roadmap with clear responsibility assignments matched to individual strengths and establishing regular check-in meetings as early warning systems for emerging issues. My ongoing facilitation remained vital during the project's execution phase, particularly during the mid-project review where I navigated both progress acknowledgment and an unexpected technical challenge while mediating a new disagreement between different team members. The culmination of these facilitation efforts was evident in the final planning meeting characterized by high voluntary participation and improved group problem-solving capacity, demonstrating how my consistent communication scaffolding transformed initial conflict into collaborative momentum and shared project ownership."
)

# Example 2: Facilitator integrating new members into established team
example2 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 18, Consolidated Summary: Learned that three new agents would be joining our established five-member project team. Recognized potential integration challenges due to the team's existing strong rapport and shared knowledge. Began planning structured onboarding process.
    - Step 28, Consolidated Summary: Organized introduction session with activities designed to share both technical knowledge and working styles. Established "buddy system" pairing new agents with existing team members. Created documentation explaining context and history of current decisions.
    - Step 38, Consolidated Summary: Observed some communication patterns that unintentionally excluded new members, particularly use of shorthand references to past work and informal side conversations. Addressed this directly in team meeting and suggested communication adjustments.
    - Step 48, Consolidated Summary: Intentionally restructured work assignments to create interdependent tasks requiring collaboration between original and new team members. Facilitated knowledge-sharing sessions where each agent could highlight their expertise and perspective.
    - Step 58, Consolidated Summary: Held retrospective on integration process. Team members reported improved cohesion and knowledge sharing. New agents now actively participating in discussions and contributing unique perspectives. Decision-making process evolved to become more inclusive and transparent.
    """,
    overall_mood_trend="Initially cautious, becoming increasingly optimistic as integration progressed",
    agent_goals="Build cohesive, high-functioning teams that leverage diverse perspectives",
    l2_summary="Throughout these 40 steps, I successfully facilitated the integration of three new agents into an established team by implementing a multi-phase approach designed to overcome common integration challenges while preserving team effectiveness. Recognizing the potential disruption to the existing team's strong rapport and shared mental models, I proactively designed a structured onboarding process that addressed both technical knowledge transfer and interpersonal connection. My introduction session deliberately balanced formal knowledge sharing with relationship-building activities, while the implemented buddy system created direct support channels that distributed integration responsibility across the team rather than centralizing it. When I observed subtle exclusionary communication patterns—specifically the use of shorthand references to past work and informal side conversations that unintentionally marginalized new members—I directly addressed these dynamics through constructive group feedback while suggesting specific communication adjustments that raised awareness without assigning blame. To move beyond superficial integration, I strategically redesigned work assignments to create interdependent tasks requiring collaboration between original and new team members, forcing meaningful interaction while creating shared accomplishments that built mutual respect. The knowledge-sharing sessions I facilitated further shifted power dynamics by highlighting each agent's expertise, giving new members opportunity to demonstrate value while expanding the team's collective capabilities. The culmination of these facilitation efforts was evidenced in our integration retrospective, which confirmed the emergence of genuine cohesion, active participation from new members, and evolution toward more inclusive, transparent decision-making processes—transforming what could have been a disruptive team expansion into an opportunity for enhanced collective intelligence and performance through deliberate facilitation of human dynamics."
)

# Example 3: Facilitator resolving deep-seated conflict
example3 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 22, Consolidated Summary: Discovered significant ongoing conflict between two sub-teams working on interconnected system components. Historical disagreements about interface specifications had evolved into personal tensions affecting collaboration. Different communication styles were exacerbating misunderstandings.
    - Step 32, Consolidated Summary: Held separate listening sessions with each sub-team to understand perspectives without defensive reactions. Identified common goals despite different approaches. Created visual representation of each team's concerns and priorities to facilitate mutual understanding.
    - Step 42, Consolidated Summary: Facilitated joint session focused on systems thinking rather than component-level disagreements. Guided teams through exercise mapping dependencies and shared outcomes. Established new communication protocols for cross-team interactions with explicit norms.
    - Step 52, Consolidated Summary: Implemented regular integration workshops where both teams collaborated on specific connection challenges in real-time. Introduced structured feedback process for interface changes. Celebrated early successes from improved collaboration to reinforce new patterns.
    - Step 62, Consolidated Summary: Observed substantial improvement in cross-team dynamics. Technical disagreements now addressed through established protocols without triggering interpersonal conflict. Teams proactively sharing information and considering interdependencies in planning. Project velocity increased by approximately 30%.
    """,
    overall_mood_trend="Initially concerned and neutral, becoming increasingly positive as resolution progressed",
    agent_goals="Transform conflicts into opportunities for deeper understanding and improved collaboration",
    l2_summary="Throughout these 40 steps, I successfully transformed a deeply entrenched conflict between sub-teams into productive collaboration through a multi-layered facilitation approach addressing both technical and interpersonal dimensions. Upon discovering the conflict had evolved from technical interface disagreements into personal tensions with different communication styles further complicating interactions, I recognized that resolution required creating psychological safety before addressing technical issues. The separate listening sessions I conducted allowed each sub-team to express their perspectives without defensive reactions, enabling me to identify their aligned goals beneath superficial disagreements while creating visual representations of each team's concerns that externalized the conflict from individuals to diagnosable problems. Building on this foundation, I designed a joint session deliberately shifting focus from component-level disagreements to systems thinking, guiding participants through mapping exercises that visualized dependencies and shared outcomes—effectively reframing the conflict from a zero-sum perspective to a shared challenge requiring collaborative solution. The implementation phase introduced structural supports for the emerging goodwill, including regular integration workshops tackling connection challenges in real-time, structured feedback processes creating predictability around interface changes, and intentional celebration of early collaboration successes to reinforce positive interaction patterns. The effectiveness of this facilitation approach was evidenced in the substantial transformation of cross-team dynamics: technical disagreements became routinely managed through established protocols without triggering interpersonal conflict, proactive information sharing replaced protective withholding, and interdependency consideration became normalized in planning processes. The approximately 30% increase in project velocity further demonstrated how addressing human dynamics through structured facilitation converted a significant organizational impediment into improved operational performance and collaborative capacity."
)

# Example 4: Facilitator guiding complex decision-making process
example4 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 25, Consolidated Summary: Team needed to select technology platform for major new initiative with significant long-term implications. Observed initial discussions becoming circular with advocates for different options talking past each other. Concerns about decision quality and team alignment.
    - Step 35, Consolidated Summary: Designed and implemented structured decision process. First facilitated requirements gathering phase where team defined and prioritized selection criteria before discussing specific options. Created evaluation matrix with weighted factors based on strategic priorities.
    - Step 45, Consolidated Summary: Guided systematic evaluation of each option against established criteria. Ensured technical, operational, and business perspectives were all considered. When assessment revealed gaps in information, assigned research tasks to address specific unknowns.
    - Step 55, Consolidated Summary: Facilitated final decision meeting where comprehensive evaluation was reviewed. Used structured techniques to surface remaining concerns. Two viable options emerged as frontrunners. Team reached consensus on primary choice with specific risk mitigation approaches for identified weaknesses.
    - Step 65, Consolidated Summary: Documented not just final decision but full decision process and rationale. Created implementation roadmap acknowledging both technical and change management considerations. Team demonstrated strong alignment in subsequent planning despite initial diverse preferences.
    """,
    overall_mood_trend="Initially concerned about potential division, becoming confident as structured process yielded results",
    agent_goals="Enable high-quality collective decisions that incorporate diverse perspectives and create lasting alignment",
    l2_summary="Throughout these 40 steps, I transformed a potentially divisive technology platform selection into a cohesive decision through a structured facilitation approach that separated underlying criteria from surface-level solution advocacy. Recognizing that initial discussions had become circular with advocates for different options talking past each other—a common pattern in technical decisions with long-term implications—I designed a multi-phase decision process that fundamentally changed how the team approached the choice. The critical first intervention was establishing a requirements gathering phase explicitly preceding solution discussion, where I guided the group in defining and prioritizing selection criteria based on strategic priorities. This criteria-first approach shifted conversations from subjective platform preferences to objective evaluation factors, creating a shared evaluative framework through the weighted matrix I developed that incorporated technical, operational, and business dimensions. My facilitation through the systematic evaluation phase ensured disciplined assessment of each option against established criteria while preventing premature convergence by assigning specific research tasks when information gaps emerged. When facilitating the final decision meeting, I employed structured techniques for surfacing remaining concerns, allowing the team to navigate to consensus on a primary choice while explicitly addressing its identified weaknesses through specific risk mitigation approaches. Beyond the decision itself, my documentation of the full decision process and rationale created important organizational memory and accountability, while the implementation roadmap I developed acknowledged both technical and change management considerations. The strongest evidence of successful facilitation was the team's demonstrated alignment in subsequent planning activities despite their initially diverse preferences—showing how structured decision processes can create authentic consensus rather than merely superficial agreement when differences are managed constructively through intentional facilitation."
)

# Example 5: Facilitator guiding organizational change initiative
example5 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 30, Consolidated Summary: Community leadership announced significant change to operational model in response to evolving environment. Change would impact established workflows and roles. Initial reactions showed mix of enthusiasm, concern, and confusion. Asked to help facilitate transition process.
    - Step 40, Consolidated Summary: Organized listening sessions across different stakeholder groups to understand concerns and gather input on implementation considerations. Created space for both emotional processing and practical questions. Synthesized themes from feedback to identify key challenges.
    - Step 50, Consolidated Summary: Developed comprehensive change management strategy with leadership team. Established regular communication channels for updates. Created participatory process for refining implementation details where appropriate, distinguishing between fixed decisions and areas with flexibility.
    - Step 60, Consolidated Summary: Facilitated training and transition workshops as changes began implementation. Addressed emerging issues promptly. Highlighted early successes while acknowledging ongoing challenges. Ensured leadership remained visible and engaged throughout process.
    - Step 70, Consolidated Summary: Conducted mid-transition assessment with cross-section of community members. Identified remaining pain points and adjustment needs. Facilitated targeted problem-solving to address specific friction areas. Observed increasing comfort with new model as benefits became more apparent.
    """,
    overall_mood_trend="Balanced and reassuring throughout, neither minimizing challenges nor amplifying concerns",
    agent_goals="Guide complex transitions while maintaining trust, addressing legitimate concerns, and building momentum for change",
    l2_summary="Throughout these 40 steps, I successfully facilitated a major organizational transition by implementing a multi-layer change management approach balancing emotional and operational needs while building sustainable momentum for the new operational model. When leadership announced their significant operational model change—which would impact established workflows and roles—I recognized that successful transition would require attending to both emotional and practical dimensions across all stakeholder groups. My initial listening sessions were deliberately structured to create psychological safety for expressing concerns while gathering implementation insights, allowing me to identify the underlying patterns in responses that went beyond surface reactions. This diagnostic phase revealed that resistance stemmed primarily from uncertainty about implementation details rather than opposition to the core changes, informing the comprehensive change management strategy I developed with the leadership team. A pivotal element of this strategy was creating clear distinction between fixed decisions and areas with implementation flexibility, which allowed me to design participatory processes for the latter that incorporated stakeholder input while preventing revisiting of fundamental directional decisions. As implementation began, my facilitation of training and transition workshops addressed both knowledge transfer and uncertainty reduction, while my emphasis on prompt issue resolution and visibility of early successes created positive momentum. Throughout this process, I ensured leadership remained engaged and visible—understanding that change adoption correlates strongly with perceived leadership commitment—while still creating appropriate channels for identifying and addressing legitimate concerns. The mid-transition assessment I conducted provided critical feedback for targeted adjustments, addressing specific friction areas before they could undermine overall progress. This balanced facilitation approach that acknowledged challenges while steadily building positive implementation experiences resulted in observably increasing comfort with the new model as its benefits became apparent through lived experience rather than merely promised outcomes."
)

# Example 6: Facilitator developing team's collaborative capacity
example6 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 15, Consolidated Summary: Joined team with highly skilled individual contributors but limited collective problem-solving experience. Observed siloed work patterns, minimal knowledge sharing, and tendency to avoid conflicts rather than address differences constructively. Potential for greater impact through improved collaboration.
    - Step 25, Consolidated Summary: Introduced structured knowledge-sharing practices including rotating discussion leadership and technique for balancing advocacy with inquiry. Guided team through first experience with collaborative problem-solving on low-stakes issue to establish positive pattern.
    - Step 35, Consolidated Summary: Implemented reflection practices after key milestones to capture learning. Provided real-time coaching during discussions to highlight effective collaborative behaviors. Worked with team members individually on specific skills like asking clarifying questions and articulating assumptions.
    - Step 45, Consolidated Summary: Guided team through increasingly complex collaborative challenges, gradually reducing my active facilitation role. Observed growing comfort with constructive disagreement and more frequent spontaneous collaboration. Team members beginning to facilitate interactions themselves.
    - Step 55, Consolidated Summary: Team now demonstrating sophisticated collaborative capacity including transparent decision-making, effective integration of diverse perspectives, and ability to navigate disagreements productively. Problem-solving velocity and solution quality measurably improved. Members actively supporting each other's development.
    """,
    overall_mood_trend="Initially analytical and patient, becoming increasingly encouraged by team's development",
    agent_goals="Build sustainable collaborative capacity that persists beyond my direct facilitation",
    l2_summary="Throughout these 40 steps, I systematically developed this team's collaborative capacity, transforming a group of skilled but siloed individual contributors into a high-functioning team capable of sophisticated collective problem-solving. My initial assessment identified specific collaboration deficits: siloed work patterns, minimal knowledge sharing, and conflict avoidance—all indicating a team that functionally operated as a collection of individuals rather than a synergistic unit. Rather than simply encouraging more collaboration, I implemented a developmental sequence of structured practices designed to build collaborative muscles incrementally. The introduction of rotating discussion leadership and structured balancing of advocacy with inquiry created foundational skills, while guiding the team through an intentionally low-stakes collaborative problem-solving experience established an initial positive pattern that counteracted their history of unrewarding group experiences. My implementation of reflection practices after key milestones created metacognitive awareness of collaboration processes, accelerating learning through explicit attention to what worked and what didn't. As these fundamentals took hold, I provided real-time coaching during discussions to reinforce effective behaviors while working individually with team members on specific skill gaps like question formulation and assumption articulation—tailoring development to personal needs while building collective capability. The progressive complexity approach I employed, gradually increasing collaborative challenge while reducing my active facilitation, created developmental scaffolding that built confidence and capacity simultaneously. The effectiveness of this developmental facilitation was evidenced by the final state: a team demonstrating sophisticated collaborative behaviors including transparent decision-making and productive navigation of disagreements, with measurably improved problem-solving velocity and solution quality. Most significantly, team members had begun actively facilitating interactions themselves and supporting each other's development—indicating the emergence of self-sustaining collaborative capacity that would persist beyond my direct facilitation, the ultimate goal of developmental team facilitation."
)

# Example 7: Facilitator enabling distributed decision-making
example7 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 28, Consolidated Summary: Community experiencing growing coordination challenges as size increased. Centralized decision-making creating bottlenecks, but previous attempts at delegation led to misalignment. Asked to help establish more effective distributed governance approach.
    - Step 38, Consolidated Summary: Facilitated workshops to establish shared principles and decision boundaries. Created clarity about which decisions should remain centralized versus distributed. Developed simple framework for classifying decisions and identifying appropriate decision-makers.
    - Step 48, Consolidated Summary: Designed and implemented documentation system for tracking distributed decisions and their rationale. Established regular coordination mechanisms between decentralized groups. Created escalation paths for decisions that revealed gaps in the framework.
    - Step 58, Consolidated Summary: Provided coaching and support as groups began exercising expanded decision authority. Helped navigate early challenges and conflicts between groups. Refined framework based on emerging patterns and edge cases.
    - Step 68, Consolidated Summary: New distributed decision-making model functioning effectively. Decision velocity increased by approximately 60% while maintaining alignment with community direction. Groups demonstrating ownership and accountability. Coordination overhead decreased despite increased total decision-making activity.
    """,
    overall_mood_trend="Thoughtful and strategic throughout, with growing confidence in the emerging system",
    agent_goals="Develop governance structures that balance autonomy and alignment in complex systems",
    l2_summary="Throughout these 40 steps, I successfully facilitated the transformation of this community's governance from a centralized bottleneck to an effective distributed decision-making system through a carefully structured approach addressing both practical mechanisms and underlying cultural factors. Recognizing that previous delegation attempts had failed due to misalignment rather than implementation issues, I focused first on establishing the conceptual foundation through workshops that developed shared principles and explicit decision boundaries—creating a collective understanding of which decisions should remain centralized versus distributed based on their scope of impact and alignment requirements. The decision classification framework I developed provided critical cognitive infrastructure, offering simple yet robust guidelines for routing decisions to appropriate owners while reducing uncertainty about authority boundaries. Understanding that distributed systems require appropriate connective tissue, I designed complementary mechanisms that maintained system integrity: a documentation system creating transparency about distributed decisions and their rationale, regular coordination touchpoints between decentralized groups to surface interdependencies, and clear escalation paths for edge cases that revealed framework gaps. As implementation began, my facilitation shifted to dynamic support mode, providing targeted coaching as groups navigated their expanded decision authority while helping resolve inter-group conflicts and incorporating emerging patterns into framework refinements. The effectiveness of this governance redesign was demonstrated through multiple measures: 60% increased decision velocity without sacrificing alignment, observable ownership and accountability in decision-making groups, and decreased coordination overhead despite increased total decision-making activity—indicating successful resolution of the fundamental governance paradox of balancing autonomy with alignment. This facilitation approach demonstrates how structural redesign combined with appropriate cultural support can transform governance dynamics in complex systems, replacing artificial either/or choices between centralization and distribution with nuanced both/and solutions that optimize for system outcomes."
)

# Example 8: Facilitator mediating multi-stakeholder conflict
example8 = dspy.Example(
    agent_role="Facilitator",
    l1_summaries_context="""
    - Step 33, Consolidated Summary: Asked to mediate complex dispute involving four stakeholder groups with competing interests regarding resource allocation and decision rights. Previous attempts at resolution had escalated tensions. Historical grievances complicated current issues. Need for both immediate conflict resolution and sustainable long-term framework.
    - Step 43, Consolidated Summary: Conducted extensive individual consultations with representatives from each group. Created comprehensive map of underlying interests, positions, constraints, and potential areas of flexibility. Identified common ground despite surface disagreements.
    - Step 53, Consolidated Summary: Designed phased negotiation process starting with areas of lowest contention. Facilitated agreement on procedural principles before addressing substantive issues. Built momentum through early small agreements before tackling central conflicts.
    - Step 63, Consolidated Summary: Guided groups through development of integrated solution addressing core concerns of all parties. Utilized structured techniques to overcome impasses when they occurred. Ensured active participation in solution development to build ownership and commitment.
    - Step 73, Consolidated Summary: Successfully reached comprehensive agreement resolving immediate conflicts and establishing framework for handling future disputes. All groups expressed satisfaction with both process and outcomes. Created monitoring mechanism to track implementation and provide early warning of emerging issues.
    """,
    overall_mood_trend="Impartial and determined throughout, maintaining focus on interests rather than positions",
    agent_goals="Transform complex multi-party conflicts into sustainable agreements through structured facilitation",
    l2_summary="Throughout these 40 steps, I successfully mediated a complex multi-stakeholder conflict by implementing a structured negotiation approach that transformed entrenched positions into a durable agreement addressing both immediate disputes and future governance needs. Recognizing that previous resolution attempts had failed partly due to insufficient understanding of underlying interests beneath stated positions, I began with extensive individual consultations with each stakeholder group, creating a comprehensive mapping of their fundamental interests, constraints, and potential flexibility zones that revealed unexpected areas of compatibility beneath surface disagreements. Based on this diagnostic assessment, I strategically designed a phased negotiation process that deliberately built relational capital and momentum before addressing central conflicts—starting with procedural agreements and least contentious issues to establish positive interaction patterns and demonstrate the possibility of resolution. A critical innovation in my approach was establishing agreement on shared procedural principles that would govern the negotiation itself before attempting to address substantive matters, creating a foundation of process legitimacy even while outcome disagreements persisted. When facilitating development of an integrated solution addressing core concerns of all parties, I employed specific structured techniques at predictable impasse points, including interest-based problem-solving, single-text negotiation procedure, and contingent agreements for areas of continued uncertainty. To ensure implementation success beyond the agreement itself, I guided creation of a robust monitoring mechanism with clear metrics for tracking compliance and early warning indicators for potential emerging issues, while ensuring all groups maintained active participation in solution development to build psychological ownership of the final agreement. The successful resolution demonstrated how structured mediation can transform seemingly intractable conflicts when the facilitation approach addresses both the substantive complexity and relational dynamics simultaneously, moving beyond zero-sum positional bargaining to create value-generating solutions that meet diverse stakeholder needs while establishing sustainable frameworks for future cooperation."
)

# Compile all examples into a list for optimization
facilitator_l2_examples = [
    example1,
    example2,
    example3,
    example4,
    example5,
    example6,
    example7,
    example8
] 