[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sample-plugin"
version = "0.1.0"
description = "Sample Culture plug-in"
readme = "README.md"
requires-python = ">=3.10"

[project.entry-points."culture.plugins"]
sample_plugin = "sample_plugin:setup"
