name: "Setup Python"
description: "Checkout repository, load environment variables, set up Python with caching, and install dependencies"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Load environment variables
      if: hashFiles('.env') != ''
      shell: bash
      run: |
        while read -r line; do
          if [[ $line =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
            echo "$line" >> "$GITHUB_ENV"
          fi
        done < .env

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Check locked requirements (prod and dev)
      shell: bash
      run: bash scripts/check_requirements.sh

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --extra-index-url https://download.pytorch.org/whl/cu121 torch==2.3.0+cu121
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
