name: UI

on:
  push:
    branches: [main]
    paths:
      - 'culture-ui/**'
      - '.github/**'
      - 'pnpm-workspace.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'culture-ui/**'
      - '.github/**'
      - 'pnpm-workspace.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.diff.outputs.CODE_CHANGES }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect non-comment code changes
        id: diff
        run: bash scripts/check_code_changes.sh

  build:
    needs: changes
    if: needs.changes.outputs.code_changed == 'true'
    runs-on: ["self-hosted", "linux"]
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables
        if: hashFiles('.env') != ''
        shell: bash
        run: |
          while read -r line; do
            if [[ $line =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
              echo "$line" >> "$GITHUB_ENV"
            fi
          done < .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm --filter culture-ui lint

      - name: Run type check
        run: pnpm --filter culture-ui type-check

      - name: Run tests
        run: pnpm --filter culture-ui test

      - name: Build
        run: pnpm --filter culture-ui build

      - name: Install Playwright browsers
        run: pnpm --filter culture-ui exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm --filter culture-ui test:e2e
